---
- name: creates
  file:
    path: /var/test
    state: directory


- name: mount the point
  command:
    cmd: sudo mount 172.31.45.32:/var/nfs/general /nfs/general
    creates: /var/test


#- name: moount
 # command: sudo mount 172.31.45.32:/home /nfs/home