---
- name: mount the point
  command: sudo mount 172.31.45.32:/var/nfs/general /nfs/general
  args:
    creates: "/nfs/abcd.txt"


- name: moount
  command: mount -t nfs4 172.31.45.32:/home/nfs /home/nfs

  args:
    creates: "/nfs/abcd.txt"




- name: for idempotent
  copy:
    content: 'hello nfs'
    dest: /home/abcd.txt    