---
- name: create the general directory
  file:
    path: /var/nfs/general
    state: directory
    owner: root
    group: root


- name:  crete the home directory
  file:
    path: /nfs/home
    state: directory
    owner: root
    group: root  


    

