---
- name: we’ll add the repository key to the system.
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
    state: present




- name: we’ll append the Debian package repository address to the server’s sources.list
  apt_repository:
    repo: 'deb https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list'
    state: present



- include_tasks: update.yml


- name: install jenkins
  apt:
    name: jenkins
    state: present


- name: start jenkins
  service:
    name: jenkins
    state: started    