---
- name: jenkins password
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  shell: hostname
  changed_when: false
  register: result

- name: print init password jenkins
  debug:
    var: result.stdout